<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

| Terms      | Definitions                                                                                                          |
|------------|----------------------------------------------------------------------------------------------------------------------|
| Subsetting | _Selecting data_                                                                                                     |
| Indexing   | Choosing a specific element via its index                                                                            |
| Slicing    | Selecting a set of elements from the whole array or list that is stored, in their indexed order depending  on steps. |
| Masking    | Selecting an element based on given condition(s)                                                                     |

In [2]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
firstrow = np.array(np_array_2d[:,0])
firstrow = firstrow.astype(int)
secondrow = np.array(np_array_2d[:,1])
isodd = firstrow%2 != 0
print(secondrow[isodd])

#[x[1] for x in np_array_2d if x[0]%2==1]


#i totally used the wrong thing to solve it

#isodd=pd.DataFrame.to_numpy(isodd)
#print(isodd)
#print(np_array_2d)

#test = isodd.loc[0]
#print(test)

['A' 'C' 'E' 'G' 'I']


In [9]:
x=np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

x[x<50] = -1
x[x>50] = 1
x[x==50] = 0
print(x)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
